streetData = [["Gå", -4000, None, None, None, None],								
			["Västerlånggatan", 1200, None, None, None, None],
			["Allmänning", None, None, None, None, None],
			["Hornsgatan", 1200, None, None, None, None],
			["Inkomstskatt", None, None, 4000, None, None],
			["Södra station", 4000, None, None, None, None],
			["Folkungagatan", 2000, None, None, None, None],
			["Chans", None, None, None, None, None],
			["Götgatan", 2000, 1000, [100, 550, 1700, 5150, 7600, 9500], 1000],
			["Rinvägen", 2400, None, None, None, None],
			["Fängelse", None, None, None, None, None],
			["S:t Eriksgatan", 2800, None, None, None, None],
			["Elverket", 3000, None, None, None, None],
			["Odengatan", 2800, None, None, None, None],
			["Valhallavägen", 3300, None, None, None, None],
			["Östra station", 4000, None, None, None, None],
			["Sturegatan", 3600, None, None, None, None],
			["Allmänning", None, None, None, None, None],
			["Karlavägen", 3600, None, None, None, None],
			["Narvavägen", 4000, None, None, None, None],
			["Fri parkering", None, None, None, None, None],
			["Strandvägen", 4400, None, None, None, None],
			["Chans", None, None, None, None, None],
			["Kungsträdgårdsgatan", 4400, None, None, None, None],
			["Hamngatan", 4800, None, None, None, None],
			["Centralstation", 4000, None, None, None, None],
			["Vasagatan", 5200, None, None, None, None],
			["Kungsgatan", 5200, None, None, None, None],
			["Vattenreninsverket", 3000, None, None, None, None],
			["Stureplan", 5600, None, None, None, None],
			["Gå i fängelse", None, None, None, None, None],
			["Gustav Adolfs torg", 6000, None, None, None, None],
			["Drottninggatan", 6000, None, None, None, None],
			["Allmänning", None, None, None, None, None],
			["Diplomatstaden", 6400, None, None, None, None],
			["Norra station", 4000, None, None, None, None],
			["Chans", None, None, None, None, None],
			["Centrum", 7000, None, None, None, None],
			["Lyxskatt", None, None, 2000, None, None],
			["Norrmalmstorg", 8000, None, None, None, None]]