
#			name, price, housePrice, rent, mortgageValue, owner, set
streetData = [["Gå", None, None, [-4000], None, "Bank", None],								
			["Västerlånggatan", 1200, None, [0], None, "City", ["Västerlånggatan","Hornsgatan"]],
			["Allmänning", None, None, [0], None, "Bank", None],
			["Hornsgatan", 1200, None, [0], None, "City", ["Västerlånggatan","Hornsgatan"]],
			["Inkomstskatt", None, None, [4000], None, "Bank", None],
			["Södra station", 4000, None, None, None, "City", ["Södra station", "Östra station", "Norra staion", "Centralstation"]],
			["Folkungagatan", 2000, None, None, None, "City", ["Folkungagatan", "Götgatan", "Ringvägen"]],
			["Chans", None, None, None, None, "Bank", None],
			["Götgatan", 2000, 1000, [100, 550, 1700, 5150, 7600, 9500], 1000, "City", ["Folkungagatan", "Götgatan", "Ringvägen"]],
			["Ringvägen", 2400, None, None, None, "City", ["Folkungagatan", "Götgatan", "Ringvägen"]],
			["Fängelse", None, None, None, None, "Bank", None],
			["S:t Eriksgatan", 2800, None, None, None, "City", ["S:t Eriksgatan", "Odengatan", "Valhallavägen"]],
			["Elverket", 3000, None, None, None, "City", ["Elverket", "Vattenreningsverket"]],
			["Odengatan", 2800, None, None, None, "City", ["S:t Eriksgatan", "Odengatan", "Valhallavägen"]],
			["Valhallavägen", 3300, None, None, None, "City", ["S:t Eriksgatan", "Odengatan", "Valhallavägen"]],
			["Östra station", 4000, None, None, None, "City", ["Södra station", "Östra station", "Norra staion", "Centralstation"]],
			["Sturegatan", 3600, None, None, None, "City", ["Sturegatan", "Karlavägen", "Narvavägen"]],
			["Allmänning", None, None, None, None, "Bank", None],
			["Karlavägen", 3600, None, None, None, "City", ["Sturegatan", "Karlavägen", "Narvavägen"]],
			["Narvavägen", 4000, None, None, None, "City", ["Sturegatan", "Karlavägen", "Narvavägen"]],
			["Fri parkering", None, None, None, None, "Bank", None],
			["Strandvägen", 4400, None, None, None, "City", ["Strandvägen", "Kungsträdgårdsgatan", "Hamngatan"]],
			["Chans", None, None, None, None, "Bank", None],
			["Kungsträdgårdsgatan", 4400, None, None, None, "City", ["Strandvägen", "Kungsträdgårdsgatan", "Hamngatan"]],
			["Hamngatan", 4800, None, None, None, "City", ["Strandvägen", "Kungsträdgårdsgatan", "Hamngatan"]],
			["Centralstation", 4000, None, None, None, "City", ["Södra station", "Östra station", "Norra staion", "Centralstation"]],
			["Vasagatan", 5200, None, None, None, "City", ["Vasagatan", "Kungsgatan", "Stureplan"]],
			["Kungsgatan", 5200, None, None, None, "City", ["Vasagatan", "Kungsgatan", "Stureplan"]],
			["Vattenreninsverket", 3000, None, None, None, "City", ["Elverket", "Vattenreningsverket"]],
			["Stureplan", 5600, None, None, None, "City", ["Vasagatan", "Kungsgatan", "Stureplan"]],
			["Gå i fängelse", None, None, None, None, "Bank", None],
			["Gustav Adolfs torg", 6000, None, None, None, "City", ["Gustav Adolfs torg", "Drottninggatan", "Diplomatstaden"]],
			["Drottninggatan", 6000, None, None, None, "City", ["Gustav Adolfs torg", "Drottninggatan", "Diplomatstaden"]],
			["Allmänning", None, None, None, None, "Bank", None],
			["Diplomatstaden", 6400, None, None, None, "City", ["Gustav Adolfs torg", "Drottninggatan", "Diplomatstaden"]],
			["Norra station", 4000, None, None, None, "City", ["Södra station", "Östra station", "Norra staion", "Centralstation"]],
			["Chans", None, None, None, None, "Bank", None],
			["Centrum", 7000, None, None, None, "City", ["Centrum", "Norrmalmstorg"]],
			["Lyxskatt", None, None, 2000, None, "Bank", None],
			["Norrmalmstorg", 8000, None, None, None, "City", ["Centrum", "Norrmalmstorg"]]]